line-length = 120

[lint]
select = ["E", "F", "I", "W"]
ignore = ["E501", "E712", "F601", "F403", "W291", "W293"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"**/alembic/env.py" = ["E402"]
"**/alembic/versions/*.py" = ["E501", "I001"]
"**/tests/**/*.py" = ["E402", "F401", "F841"]
